### ISSUE TITLE
NullRef when loading "Lone Targets"

### ISSUE THREAD

**Issue by FroggieFrog** [fremag/MemoScope.Net#202]
The log file contains no valueable information.
I attached the copied rows from the LogModule.
Dump file can not be send, because of regulations.
[memoscope_nullref.txt](https://github.com/fremag/MemoScope.Net/files/1639248/memoscope_nullref.txt)

**Comment by fremag** [comment]
Hi,

I'm sorry you have this bug but unfortunately, without the dump file, I can't reproduce it.
I've loaded some of my dump files and had no issue.
I understand why you can't send yours.

Do you run Memoscope with the compiled binaries or with the source code/Visual Studio ?
If you can run it in debug mode, could you put a conditional breakpoint here:
![image](https://user-images.githubusercontent.com/14943271/35186041-190b82e0-fe0e-11e7-9641-6afbd5b3027f.png)

then send me the value of "Type" variable ?
I'd like to see why this type is seen as an array type in the 'Lone target' analysis but has no component type.

**Comment by FroggieFrog** [comment]
Originally I started it via binaries.
Now I started it via Visual Studio and used QuickWatch for "Type" and "Type.GetType()" (see attached files).
Also later there is a follow up NullRef:

Exception thrown: 'System.NullReferenceException' in MemoScope.exe
**loneTargetInformations** was null.

[Type.txt](https://github.com/fremag/MemoScope.Net/files/1651190/Type.txt)
[GetType.txt](https://github.com/fremag/MemoScope.Net/files/1651189/GetType.txt)
![2018_01_22_09_06_54_memoscope net_debugging_microsoft_visual_studio](https://user-images.githubusercontent.com/6222752/35211002-d2e66684-ff54-11e7-9581-1026f696eb4e.png)

**Comment by fremag** [comment]
Thanks for the feedback and details.
It's really weird because it looks like the delegate's invocation list (_invocationList field) is a simple System.Object instead of the expected array System.Object[].
So of course the ComponentType is null and then you get a NullRef exception.
Well, I'm debugging and I see that it happens only when the _invocationCount is 0 so the program doesn't loop on the expected array's items.
When _invocationCount == 1, there is no _invocationList because the handler is in _target and there is no need for an array.

Could you debug and break like you did and give me details from the previous call in the stack ?
Something like this :
![image](https://user-images.githubusercontent.com/14943271/35355633-350d9896-014e-11e8-877f-08e51aa74fa9.png)

I'm sorry to bother you but it's not easy to debug when you can reproduce the issue on your computer...

**Comment by FroggieFrog** [comment]
I noticed that there is a property "IsNull" which is "true".
![2018_01_25_09_14_38_memoscope net_debugging_microsoft_visual_studio](https://user-images.githubusercontent.com/6222752/35377660-5fcbfe8a-01b0-11e8-866e-2d8fc22f577b.png)

**Comment by fremag** [comment]
You're right.
The adress is 0 so the invocList is null and empty of course.
invocList can be null if you remove all handlers from a delegate but in this case invocCountValue == 0 .
I wonder why you have invocList == null and invocCountValue != 0...
Sometimes strange things happens if the dump is taken while GC is working, maybe it's the reason of this ?
Any way, I will add a check to avoid the exception and a warning too maybe.
```csharp
                internal static IEnumerable<ClrObject> EnumerateHandlers(ClrObject clrObject)
		{
			ClrObject target = clrObject[TargetFieldName];
			ulong targetAddress = target.Address;

			if (targetAddress != clrObject.Address)
			{
				yield return clrObject;
			}
			else
			{

				var invocCount = clrObject[InvocationCountFieldName];
				var v = invocCount.SimpleValue;
				var invocCountValue = (long)v;
				var invocList = clrObject[InvocationListFieldName];
// Check invocList is not null
				if (! invocList.IsNull)
				{
					for (int i = 0; i < invocCountValue; i++)
					{
						var targetObject = invocList[i];
						yield return targetObject;
					}
				}
			}
		}
```

**Comment by FroggieFrog** [comment]
I locally added your fix and it worked. I could analyze my dump file. Thank you.

**Comment by fremag** [comment]
You're welcome.
Thank you for your time and help to improve Memoscope.
